# Generated by Django 2.2.10 on 2021-11-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acctcust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acctcust',
        ),
    ]
