# Generated by Django 2.2.10 on 2021-12-02 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211201_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 19, 28, 17, 112948)),
        ),
    ]
